#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "usage: scripts/build_release_assets.sh vX.Y-candidate.Z [out-dir]" >&2
  exit 2
fi

TAG="$1"
OUT_DIR="${2:-dist/release}"

if [[ "$TAG" != v* ]]; then
  echo "release tag must start with v: $TAG" >&2
  exit 2
fi

expected_version="${TAG#v}"
if ! git show "${TAG}:CITATION.cff" | grep -Fq "version: \"$expected_version\""; then
  echo "tag $TAG does not match CITATION.cff version $expected_version" >&2
  exit 1
fi

commit="$(git rev-parse --verify "${TAG}^{commit}")"
archive_name="agent-assurance-case-${TAG}.tar.gz"
archive="$OUT_DIR/$archive_name"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

git archive \
  --format=tar.gz \
  --prefix="agent-assurance-case-${TAG}/" \
  --output="$archive" \
  "$commit"

archive_sha="$(shasum -a 256 "$archive" | awk '{print $1}')"
printf '%s  %s\n' "$archive_sha" "$archive_name" > "${archive}.sha256"

python3 - "$TAG" "$commit" "$archive_name" "$archive_sha" "$OUT_DIR" <<'PY'
import json
import sys
from pathlib import Path

tag, commit, archive_name, archive_sha, out_dir = sys.argv[1:]
manifest = {
    "schema_version": "aac.release-manifest.v0.1",
    "artifact": "agent-assurance-case",
    "tag": tag,
    "commit": commit,
    "entries": [
        {
            "path": archive_name,
            "sha256": archive_sha,
            "role": "release-source-bundle",
        }
    ],
    "provenance_note": (
        "Release asset manifest built from the signed tag commit. GitHub "
        "artifact attestations, when generated by release-assets.yml, bind "
        "the uploaded files to the GitHub Actions workflow run."
    ),
}
Path(out_dir, "RELEASE-MANIFEST.json").write_text(
    json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    encoding="utf-8",
)
PY

{
  shasum -a 256 "$archive"
  shasum -a 256 "${archive}.sha256"
  shasum -a 256 "$OUT_DIR/RELEASE-MANIFEST.json"
} | sed "s#  $OUT_DIR/#  #" > "$OUT_DIR/SHA256SUMS"

(cd "$OUT_DIR" && shasum -a 256 -c "${archive_name}.sha256")

printf 'release assets written to %s\n' "$OUT_DIR"
find "$OUT_DIR" -maxdepth 1 -type f -print | sort
